//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IS_CS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Darbuotoja
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Darbuotoja()
        {
            this.Saskaitas = new HashSet<Saskaita>();
            this.Remontuojamas_irenginys = new HashSet<Remontuojamas_irenginys>();
            this.Prekes = new HashSet<Preke>();
            this.Uzsakymas = new HashSet<Uzsakyma>();
            this.Patvirtinimas = new HashSet<Patvirtinima>();
        }
    
        public int paskyros_id { get; set; }
        public string prisjungimas { get; set; }
        public string slaptazodis { get; set; }
        public string vardas { get; set; }
        public string pavarde { get; set; }
        public string el_pastas { get; set; }
        public string tel_nr { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Saskaita> Saskaitas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Remontuojamas_irenginys> Remontuojamas_irenginys { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Preke> Prekes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Uzsakyma> Uzsakymas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Patvirtinima> Patvirtinimas { get; set; }
    }
}
