//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IS_CS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class is_kpEntities : DbContext
    {
        public is_kpEntities()
            : base("name=is_kpEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Darbuotoja> Darbuotojas { get; set; }
        public virtual DbSet<Gedimo_busena> Gedimo_busena { get; set; }
        public virtual DbSet<Grazinimo_busena> Grazinimo_busena { get; set; }
        public virtual DbSet<Grazinimo_busenos> Grazinimo_busenos { get; set; }
        public virtual DbSet<Grazinimo_priezastis> Grazinimo_priezastis { get; set; }
        public virtual DbSet<Irenginio_busena> Irenginio_busena { get; set; }
        public virtual DbSet<Kategorija> Kategorijas { get; set; }
        public virtual DbSet<Kiekio_tipas> Kiekio_tipas { get; set; }
        public virtual DbSet<Mokejimo_budas> Mokejimo_budas { get; set; }
        public virtual DbSet<Preke> Prekes { get; set; }
        public virtual DbSet<Prekiu_krepselis> Prekiu_krepselis { get; set; }
        public virtual DbSet<priklauso> priklausoes { get; set; }
        public virtual DbSet<Pristatymo_budai> Pristatymo_budai { get; set; }
    }
}
