//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IS_CS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gedima
    {
        public string tipas { get; set; }
        public System.DateTime pataisymo_data { get; set; }
        public int busena { get; set; }
        public int id_Gedimas { get; set; }
        public int fk_Remontuojamas_irenginysirenginio_id { get; set; }
    
        public virtual Gedimo_busena Gedimo_busena { get; set; }
        public virtual Remontuojamas_irenginys Remontuojamas_irenginys { get; set; }
    }
}
