//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IS_CS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Israsa
    {
        public int nr { get; set; }
        public System.DateTime data { get; set; }
        public int fk_Patvirtinimas { get; set; }
        public int fk_Klientas_paskyros_id { get; set; }
    
        public virtual Klienta Klienta { get; set; }
        public virtual Patvirtinima Patvirtinima { get; set; }
    }
}
