//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IS_CS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Klienta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Klienta()
        {
            this.Israsas = new HashSet<Israsa>();
            this.Uzsakymas = new HashSet<Uzsakyma>();
            this.Saskaitas = new HashSet<Saskaita>();
            this.Remontuojamas_irenginys = new HashSet<Remontuojamas_irenginys>();
        }
    
        public int paskyros_id { get; set; }
        public string prisjungimas { get; set; }
        public string slaptazodis { get; set; }
        public string vardas { get; set; }
        public string pavarde { get; set; }
        public string tel_nr { get; set; }
        public string e_pastas { get; set; }
        public int fk_Prekiu_krepselisprekiu_krepselio_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Israsa> Israsas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Uzsakyma> Uzsakymas { get; set; }
        public virtual Prekiu_krepselis Prekiu_krepselis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Saskaita> Saskaitas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Remontuojamas_irenginys> Remontuojamas_irenginys { get; set; }
    }
}
