//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IS_CS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patvirtinima
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Patvirtinima()
        {
            this.Israsas = new HashSet<Israsa>();
        }
    
        public int patvirtinimas { get; set; }
        public int ar_preke_gali_buti_grazinta { get; set; }
        public System.DateTime data { get; set; }
        public int fk_Graznimas_nr { get; set; }
        public int fk_Darbuotojas_paskyros_id { get; set; }
    
        public virtual Darbuotoja Darbuotoja { get; set; }
        public virtual Grazinima Grazinima { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Israsa> Israsas { get; set; }
    }
}
