//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IS_CS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Preke
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Preke()
        {
            this.itraukiama_i = new HashSet<itraukiama_i>();
            this.Prekiu_krepselis = new HashSet<Prekiu_krepselis>();
            this.Prekiu_sarasas = new HashSet<Prekiu_sarasas>();
            this.priklausoes = new HashSet<priklauso>();
        }
    
        public int bar_kodas { get; set; }
        public string modelis { get; set; }
        public string pavadinimas { get; set; }
        public double pardavimo_kaina { get; set; }
        public int kiekio_tipas { get; set; }
        public int fk_Darbuotojaspaskyros_id { get; set; }
    
        public virtual Darbuotoja Darbuotoja { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<itraukiama_i> itraukiama_i { get; set; }
        public virtual Kiekio_tipas Kiekio_tipas1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prekiu_krepselis> Prekiu_krepselis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prekiu_sarasas> Prekiu_sarasas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<priklauso> priklausoes { get; set; }
    }
}
