//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IS_CS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pristatymo_budai
    {
        public int pristatymo_id { get; set; }
        public string pavadinimas { get; set; }
        public double kaina { get; set; }
        public string trukme { get; set; }
    }
}
