//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IS_CS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Remontuojamas_irenginys
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Remontuojamas_irenginys()
        {
            this.Gedimas = new HashSet<Gedima>();
        }
    
        public int irenginio_id { get; set; }
        public string pavadinimas { get; set; }
        public string modelis { get; set; }
        public System.DateTime pridavimo_data { get; set; }
        public System.DateTime atsiëmimo_data { get; set; }
        public System.DateTime garantijos_pabaigos_data { get; set; }
        public System.DateTime planuojamas_darbu_pabaigos_data { get; set; }
        public int busena { get; set; }
        public int fk_Klientaspaskyros_id { get; set; }
        public int fk_Saskaitaserija { get; set; }
        public int fk_Darbuotojaspaskyros_id { get; set; }
    
        public virtual Darbuotoja Darbuotoja { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gedima> Gedimas { get; set; }
        public virtual Irenginio_busena Irenginio_busena { get; set; }
        public virtual Klienta Klienta { get; set; }
        public virtual Saskaita Saskaita { get; set; }
    }
}
