//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IS_CS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Saskaita
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Saskaita()
        {
            this.Prekiu_sarasas = new HashSet<Prekiu_sarasas>();
            this.Remontuojamas_irenginys = new HashSet<Remontuojamas_irenginys>();
        }
    
        public int serija { get; set; }
        public int numeris { get; set; }
        public System.DateTime data { get; set; }
        public string teikejas { get; set; }
        public string pirkejas { get; set; }
        public int fk_Klientaspaskyros_id { get; set; }
        public int fk_Uzsakymasuzsakymo_id { get; set; }
        public int fk_Darbuotojaspaskyros_id { get; set; }
    
        public virtual Darbuotoja Darbuotoja { get; set; }
        public virtual Klienta Klienta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prekiu_sarasas> Prekiu_sarasas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Remontuojamas_irenginys> Remontuojamas_irenginys { get; set; }
        public virtual Uzsakyma Uzsakyma { get; set; }
    }
}
