//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IS_CS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Uzsakyma
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Uzsakyma()
        {
            this.Saskaitas = new HashSet<Saskaita>();
        }
    
        public int uzsakymo_id { get; set; }
        public Nullable<int> ar_preke_issiusta { get; set; }
        public Nullable<System.DateTime> data_ { get; set; }
        public int mokejimo_budas { get; set; }
        public int fk_Pristatymo_budaipristatymo_id { get; set; }
        public Nullable<int> fk_Prekiu_krepselisprekiu_krepselio_id { get; set; }
        public Nullable<int> fk_Darbuotojaspaskyros_id { get; set; }
        public int fk_Klientaspaskyros_id { get; set; }
        public Nullable<int> fk_Grazinimo_nr { get; set; }
    
        public virtual Darbuotoja Darbuotoja { get; set; }
        public virtual Grazinima Grazinima { get; set; }
        public virtual Klienta Klienta { get; set; }
        public virtual Mokejimo_budas Mokejimo_budas1 { get; set; }
        public virtual Prekiu_krepselis Prekiu_krepselis { get; set; }
        public virtual Pristatymo_budai Pristatymo_budai { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Saskaita> Saskaitas { get; set; }
    }
}
